version: '3.8'

services: 
  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - mysqldb
    env_file: ./.env
    ports:
      - $NODE_LOCAL_PORT:$NODE_DOCKER_PORT
  mysqldb:
    image: mysql:5.6
    command: --default-authentication-plugin=mysql_native_password
    container_name: mysql-matchmate
    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - MYSQL_DATABASE=$MYSQLDB_DATABASE
    ports:
      - $MYSQLDB_LOCAL_PORT:$MYSQLDB_DOCKER_PORT
    expose:
      - 3306
    volumes:
      - ./sql/match-mate-init.sql:/docker-entrypoint-initdb.d/0_init.sql
      - ./volumes-data:/var/lib/mysql
