version: "3.7"

services:
  proxy:
    container_name: proxy
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    restart: "unless-stopped"
    networks:
      - backend
  mysql:
    container_name: mysql
    image: mysql:5.7    
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    ports:
      - "3306:3306"
    networks:
      - backend  

  server:
    container_name: server
    build:
      context: ./
      dockerfile: Dockerfile.dev
    command: ["./wait-for-it.sh", "mysql:3306", "--", "npm", "run", "dev"]
    ports:
      - "3000:3000" 
    environment:
      MYSQL_HOST: ${DB_HOST}
      MYSQL_PORT: ${DB_PORT}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    volumes:
      - ./:/app
      - /app/node_modules
    restart: "unless-stopped"
    networks:
      - backend
    links:
      - mysql
    depends_on:
      - mysql


networks:
  backend:
    driver: bridge

volumes:
  data:
    driver: local
